# Technically does nothing
CURRENT_VERSION = '2.0.0'

ADMIN_ROLES = ['Admin']
MOD_ROLES = [*ADMIN_ROLES, 'Moderator']

# 0xRRGGBB aka HEX
MAIN_COLOR = 0x091A4C
ERROR_COLOR = 0xD86156
OFF_COLOR_1 = 0xF2B53C
OFF_COLOR_2 = 0x5F6662
INFO_COLOR = 0x3BCCB3

NATIVE_COLOR = 0x0070BB
FLUENT_COLOR = 0x765A9F
LEARNING_COLOR = 0xC54b8C
YELLOW_ROLE_COLOR = 0xFFC40C
ORANGE_ROLE_COLOR = 0xFF7518

LANGUAGE_ROLES = [NATIVE_COLOR, FLUENT_COLOR, LEARNING_COLOR]

YES_EMOJI = '✅'
NO_EMOJI = '❌'

GITHUB_LINK = 'https://github.com/Linglot/mouse'
INVITE_LINK = 'https://discord.gg/uFWNUBQ'
